# Generated by Django 3.1.3 on 2020-11-15 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('id_number', models.IntegerField()),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.IntegerField()),
                ('blood_type', models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O', 'O'), ('O+', 'O+'), ('O-', 'O-')], default='O', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Email', models.EmailField(default='none@email.com', max_length=254)),
                ('Malaria', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('Diarrheal_Diseases', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('Road_Injuries', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('Tuberculosis', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('Cough', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=20)),
                ('song_file', models.FileField(upload_to='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDoc.patient')),
            ],
        ),
    ]
