# Generated by Django 3.1.3 on 2020-11-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0005_auto_20201116_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
