# Generated by Django 3.1.3 on 2020-11-18 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0007_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
