# Generated by Django 3.1.3 on 2020-11-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0009_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('hod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MedRecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meds', models.TextField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDoc.patient')),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDoc.clinician')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientRec',
        ),
        migrations.AddField(
            model_name='clinician',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDoc.department'),
        ),
    ]
