# Generated by Django 3.1.3 on 2020-11-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0010_auto_20201118_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrecs',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
