# Generated by Django 3.1.3 on 2020-11-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0016_auto_20201118_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
