# Generated by Django 3.1.3 on 2020-11-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0018_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MyDoc.clinician'),
        ),
        migrations.AddField(
            model_name='message',
            name='clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MyDoc.clinician'),
        ),
    ]
