# Generated by Django 3.1.3 on 2020-11-20 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0023_auto_20201121_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='nees.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 22, 10, 57, 282148, tzinfo=utc), null=True),
        ),
    ]
