# Generated by Django 3.1.3 on 2020-11-22 20:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0024_auto_20201121_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='enrc.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 20, 31, 29, 238033, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_number', models.CharField(max_length=250)),
                ('doctor_name', models.CharField(max_length=250)),
                ('patient_name', models.CharField(max_length=250)),
                ('file_number', models.CharField(max_length=20)),
                ('is_doctor', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDoc.appointment')),
            ],
        ),
    ]
