# Generated by Django 3.1.3 on 2020-11-22 21:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0025_auto_20201122_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 21, 38, 29, 842595, tzinfo=utc), null=True),
        ),
    ]
