# Generated by Django 3.1.3 on 2020-11-22 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0026_auto_20201123_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 22, 11, 39, 981992, tzinfo=utc), null=True),
        ),
    ]
