# Generated by Django 3.1.3 on 2020-11-23 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0027_auto_20201123_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 10, 41, 11, 244267, tzinfo=utc), null=True),
        ),
    ]
