# Generated by Django 3.1.3 on 2020-11-23 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0028_auto_20201123_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 10, 45, 32, 518785, tzinfo=utc), null=True),
        ),
    ]
