# Generated by Django 3.1.3 on 2020-11-23 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyDoc', '0032_auto_20201123_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='consultation_number',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='file_number',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='is_doctor',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('Online Consultation', 'Online Consultation'), ('Face-Face Consultation', 'Face-Face Consultation')], default='Online Consultation', max_length=30),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MyDoc.doctor'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnslt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDoc.userappointment'),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 15, 5, 35, 259673, tzinfo=utc), null=True),
        ),
    ]
