# Generated by Django 3.1.3 on 2020-11-23 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0033_auto_20201123_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 21, 19, 10, 40781, tzinfo=utc), null=True),
        ),
    ]
