# Generated by Django 3.1.3 on 2020-11-24 12:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0036_auto_20201124_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='explanation',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 12, 29, 5, 472964, tzinfo=utc), null=True),
        ),
    ]
