# Generated by Django 3.1.3 on 2020-11-24 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0039_auto_20201124_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_check',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_check',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
