# Generated by Django 3.1.3 on 2020-11-25 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0040_auto_20201124_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_insurance',
            field=models.CharField(blank=True, choices=[('NHIF', 'NHIF'), ('Denver_Insurance', 'Denver_Insurance'), ('My_Doc', 'My_Doc')], default='NHIF', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='languages',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.CharField(default='Nairobi/Juja', max_length=100),
        ),
    ]
