# Generated by Django 3.1.3 on 2020-11-27 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyDoc', '0041_auto_20201125_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('amount_payed', models.CharField(max_length=300)),
                ('payment_mode', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card')], max_length=30)),
                ('payed_for', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recpts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
