# Generated by Django 3.1.3 on 2020-12-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0043_auto_20201204_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='weight',
            new_name='weight_kg',
        ),
    ]
