# Generated by Django 3.1.3 on 2020-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0044_auto_20201204_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='height_cm',
            field=models.FloatField(default=130),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight_kg',
            field=models.FloatField(default=65),
        ),
    ]
