# Generated by Django 3.1.3 on 2020-12-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyDoc', '0045_auto_20201204_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(editable=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(editable=False, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recrds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='user',
            field=models.ForeignKey(help_text='To which patient medication belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.ForeignKey(help_text='To which patient message belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recept',
            name='user',
            field=models.ForeignKey(help_text='To which Receipt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recpts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(blank=True, default='enrc.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDoc.department')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.TextField()),
                ('results', models.TextField()),
                ('tech_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MyDoc.labtechnician')),
                ('user', models.ForeignKey(help_text='To which patient tests belong', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
