# Generated by Django 3.1.3 on 2020-12-04 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyDoc', '0046_auto_20201204_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subject',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recrds', to=settings.AUTH_USER_MODEL),
        ),
    ]
