# Generated by Django 3.1.3 on 2020-12-10 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0015_remove_doctor_bio'),
        ('MyDoc', '0048_appointment_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dcts', to='Doctors.doctor'),
        ),
    ]
