# Generated by Django 3.1.3 on 2020-12-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0052_auto_20201211_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='waiting_status',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
