# Generated by Django 3.1.3 on 2020-12-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0019_patient'),
        ('MyDoc', '0053_appointment_waiting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='waiting_status',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dcts', to='Doctors.doctor'),
        ),
    ]
