# Generated by Django 3.1.3 on 2020-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0054_auto_20201211_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='waiting_status',
            field=models.BooleanField(default=True),
        ),
    ]
