# Generated by Django 3.1.3 on 2020-12-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0055_appointment_waiting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medrecs',
            name='clinician',
        ),
        migrations.AddField(
            model_name='medrecs',
            name='doctor',
            field=models.ForeignKey(default='Myself', on_delete=django.db.models.deletion.PROTECT, to='MyDoc.doctor'),
        ),
        migrations.AlterField(
            model_name='medrecs',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
