# Generated by Django 3.1.3 on 2020-12-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0057_auto_20201211_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medrecs',
            name='doctor',
        ),
        migrations.AddField(
            model_name='medrecs',
            name='clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MyDoc.clinician'),
        ),
    ]
