# Generated by Django 3.1.3 on 2020-12-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0059_auto_20201211_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medrecs',
            name='user',
        ),
    ]
