# Generated by Django 3.1.3 on 2020-12-11 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyDoc', '0060_remove_medrecs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrecs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meds', to=settings.AUTH_USER_MODEL),
        ),
    ]
