# Generated by Django 3.1.3 on 2020-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0061_medrecs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Juja', max_length=60, null=True),
        ),
    ]
