# Generated by Django 3.1.3 on 2020-12-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0063_auto_20201212_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A+', 'A+'), ('A-', 'A-'), ('B', 'B'), ('B+', 'B+'), ('B-', 'B-'), ('O', 'O'), ('O+', 'O+'), ('O-', 'O-')], default='O', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height_cm',
            field=models.FloatField(blank=True, default=130.0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight_kg',
            field=models.FloatField(blank=True, default=65.0),
        ),
    ]
