# Generated by Django 3.1.3 on 2020-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0064_auto_20201213_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_check',
            field=models.DateField(blank=True, default='Not yet checked'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_check',
            field=models.DateField(blank=True, default='Unknown'),
        ),
    ]
