# Generated by Django 3.1.3 on 2020-12-13 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0066_auto_20201213_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='time',
            field=models.TimeField(help_text='Time for appointment', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Strict Format YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_check',
            field=models.DateField(blank=True, default='2020-03-13', help_text='Format YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_check',
            field=models.DateField(blank=True, default='2020-03-13', help_text='Format YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='date',
            field=models.DateField(help_text='Strict Format: YYYY-MM-DD. Appointment Day', null=True),
        ),
    ]
