# Generated by Django 3.1.3 on 2020-12-13 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0067_auto_20201213_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 13, 20, 48, 36, 469663, tzinfo=utc), help_text='Strict Format: YYYY-MM-DD. Appointment Day'),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 13, 20, 48, 36, 469663, tzinfo=utc), help_text='Time for appointment'),
        ),
    ]
