# Generated by Django 3.1.3 on 2020-12-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDoc', '0068_auto_20201213_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappointment',
            name='time',
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='date',
            field=models.DateTimeField(help_text='Strict Format: YYYY-MM-DD, time. Appointment Day and time'),
        ),
    ]
