# Generated by Django 3.1.3 on 2020-12-10 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0002_auto_20201210_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default="Am a Denver's Hospital Doctor"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='nurse.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(default='Doctor', on_delete=django.db.models.deletion.CASCADE, related_name='dcts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='waiting_status',
            field=models.BooleanField(default=True),
        ),
    ]
