# Generated by Django 3.1.3 on 2020-12-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_auto_20201210_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
