# Generated by Django 3.1.3 on 2020-12-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_auto_20201210_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
