# Generated by Django 3.1.3 on 2020-12-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0014_auto_20201210_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
    ]
