# Generated by Django 3.1.3 on 2020-12-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0017_auto_20201211_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
