# Generated by Django 3.1.3 on 2020-12-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0020_auto_20201211_0118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patientss',
        ),
    ]
