# Generated by Django 3.1.3 on 2020-12-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0021_auto_20201211_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=60, null=True)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('waiting_status', models.BooleanField(default=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dakta', to='Doctors.doctor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
