# Generated by Django 3.1.3 on 2020-12-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0022_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
